### ISSUE TITLE
autofont license

### ISSUE THREAD

**Issue by chrissimpkins** [sf-playground/autofont#1]
@iamjamestl 

Added MIT license as base to get things started.  This is what we use for other tool projects but feel free to convert to any approved FLOSS license that you'd like if you prefer a different licensing model.  Feel free to change copyright to your name.  

You have full admin access to the repo.  Let me know if you have any trouble with writes/etc.

**Comment by puppetjoy** [comment]
Thanks, Chris.  MIT is fine with me.  I had to think a bit about whether we'd need some sort of [exception](http://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=blob_plain;f=COPYING.EXCEPTION;hb=HEAD) like autoconf has to make it usable in alternatively licensed projects and I think we do not, but I am not a lawyer.  Autoconf is licensed under the GPL and includes normally GPL-licensed code in the compiled configure scripts, so it needs the exception to coexist with non-GPL software.  MIT software is happy to coexist with software of any license so long as the MIT portion is available under the terms of the MIT license.

I will elect to use my name in the copyright declarations, and contributors can of course add theirs.

I will close this, though my changes aren't on the master branch.  I don't want to push unusable code to the master branch, so I will work on a separate 'dev' branch until it's at least usable.

**Comment by chrissimpkins** [comment]
:+1:
