### ISSUE TITLE
CI testing

### ISSUE THREAD

**Issue by chrissimpkins** [sf-playground/autofont#2]
Travis CI is now active on this repository

https://travis-ci.org/source-foundry/autofont

**Comment by puppetjoy** [comment]
Great!  I've got some unit testing already going on the configure script (b23d9a4) and I've configured Travis to push its compiled and tested configure/Makefile.in files back to the repository (https://github.com/source-foundry/autofont/blob/dev/.travis/push-autotools-products.sh).  Looks like the latest build was a success! https://travis-ci.org/source-foundry/autofont/builds/279095647

I'll definitely be expanding on this as the project unfolds.

**Comment by chrissimpkins** [comment]
:+1:
