### ISSUE TITLE
Concurrent build support

### ISSUE THREAD

**Issue by chrissimpkins** [sf-playground/autofont#21]
We should consider including the compilation approach used here (when multiple UFO source builds are requested) if possible:

https://github.com/source-foundry/fontmake-mp

Definite improvement in build times for those with multi core systems.

Alternatively, something like this is possible via make?

**Comment by puppetjoy** [comment]
This is working already with GNU make, for fontmake tasks and everything else.  The `-j` option lets you specify the number of jobs to run in parallel, `-k` lets you "keep going" as far as it can if there is a failure, `-l` lets you specify a load limit for the parallelism, and `-O` synchronizes the output of parallel jobs.

**Comment by chrissimpkins** [comment]
:+1:
